<?php
// @codingStandardsIgnoreFile
?>
<?php $_helper = $this->helper('WeltPixel\Multistore\Helper\Data'); ?>
<?php $_utilityHelper = $this->helper('WeltPixel\Backend\Helper\Utility'); ?>
<?php
$oneRowClass = '';
if ($_helper->displayInOneRow()) {
    $oneRowClass .= " multistore-desktop";
}
if (!$_helper->displayInOneRowMobile()) {
    $oneRowClass .= " multistore-mobile-hide";
}
?>
<?php if (count($block->getStores())>1): ?>
    <?php $bgColorStyle = $_helper->getBarBgColor() ? "style='background-color: ".$_helper->getBarBgColor() ."'" : ''?>
<div id="multistore-mobile-switcher-language"
        class="<?= /* @noEscape */ $oneRowClass ?>"
        <?= /* @noEscape */ $bgColorStyle?>
        >
    <div class="store-options">
        <ul class="weltpixel_multistore">
            <?php foreach ($block->getStores() as $_lang): ?>
                <?php if (!$_helper->canStoreBeDisplayed($_lang->getId(), $_lang->getCode())) continue; ?>
                <?php $image = $_helper->getImageUrl($_lang->getId());  ?>
                <?php $inactiveImage = $_helper->getInactiveImageUrl($_lang->getId()); ?>

                <li class="view-<?php echo $block->escapeHtml($_lang->getCode()); ?> <?php if ($_lang->getId() == $block->getCurrentStoreId()): /* @noEscape */ echo 'active'; endif; ?>  switcher-option">
                    <?php if ($_lang->getId() == $block->getCurrentStoreId()): ?>
                        <img src="<?php /* @noEscape */ echo $image ?>" alt="<?php echo $block->escapeHtml($_lang->getName()) ?>" />
                    <?php else: ?>
                        <a href="#" data-post='<?php /* @noEscape */ echo $block->getTargetStorePostData($_lang); ?>'>
                            <img src="<?php /* @noEscape */ echo $inactiveImage ?>" alt="<?php echo $block->escapeHtml($_lang->getName()) ?>" />
                        </a>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
<style>
    <?php
    $imgHeight = $_helper->getImageHeight();
    $imgWidth = $_helper->getImageWidth();
    $barWidth = $_helper->getBarWidth();
    ?>
    ul.weltpixel_multistore li img {
        height: <?php /* @noEscape */ echo $imgHeight; ?>;
        <?php if ($imgWidth) : ?>
        width: <?php /* @noEscape */ echo $imgWidth; ?>;
        <?php endif; ?>
    }
    <?php if(!$_utilityHelper->isPearlThemeUsed() && $barWidth):?>
    @media screen and (min-width: 768px) {
        .weltpixel_multistore {
            max-width: <?php /* @noEscape */ echo $barWidth;?>
        }
    }
    <?php endif;?>
</style>
<?php endif; ?>
